/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package retailmanagement;

import java.sql.Connection;
import java.util.Random;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static retailmanagement.Signup.DBPASS;
import static retailmanagement.Signup.DBURL;
import static retailmanagement.Signup.DBUSER;

/**
 *
 * @author Aalekh
 */
public class takeOrder extends javax.swing.JFrame {
    String uname,pName;

    /**
     * Creates new form takeOrder
     */
    public takeOrder() {
        initComponents();
    }
    public takeOrder(String user,String prodName){
        uname = user;
        pName = prodName;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("SF UI Display", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter order details:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 6, 350, 50);

        jLabel2.setFont(new java.awt.Font("SF UI Display", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("City:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 230, 66, 29);

        jLabel3.setFont(new java.awt.Font("SF UI Display", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("State:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 280, 80, 29);

        jLabel4.setFont(new java.awt.Font("SF UI Display", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PinCode:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 330, 120, 29);

        jTextField1.setFont(new java.awt.Font("SF UI Display", 0, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(440, 220, 230, 40);

        jTextField2.setFont(new java.awt.Font("SF UI Display", 0, 24)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(440, 270, 230, 41);

        jTextField3.setFont(new java.awt.Font("SF UI Display", 0, 24)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(440, 320, 230, 40);

        jButton1.setFont(new java.awt.Font("SF UI Display", 1, 24)); // NOI18N
        jButton1.setText("Confirm Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 410, 190, 70);

        jButton2.setFont(new java.awt.Font("SF UI Display", 1, 24)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(960, 10, 101, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/retailmanagement/assets/saplings6.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-5, 1, 1090, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ResultSet rs;
        String oEmail=null,prodCode=null,prodPrice=null,oid=null;
        int chckflag=-1;
        try{
        String oCity    = jTextField1.getText();
        String oState   = jTextField2.getText();
        String oPincode = jTextField3.getText();
        
        DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
        Connection con = DriverManager.getConnection(DBURL, DBUSER, DBPASS);
        Statement stmt = con.createStatement();
        
        do{
        chckflag=-1;    
        Random randobj = new Random();
        int order = 10000+randobj.nextInt(10000);
        oid = "OR-"+order;
        String chcksql="select * from orderdetails";
        rs = stmt.executeQuery(chcksql);
        while(rs.next()){
            if(oid == rs.getString("orderid")){
                chckflag = 1;
                break;
            }
        }
        }while(chckflag==1);
        
        
        String sql = "select * from  customer where cname ='"+uname+"'";
        rs = stmt.executeQuery(sql);
        while(rs.next()){
            oEmail = rs.getString("emailid");
        }
        
        sql= "select * from product where prodname='"+pName+"'";
        rs = stmt.executeQuery(sql);
        while(rs.next()){
            prodCode=rs.getString("prodcode");
            prodPrice=rs.getString("price");
        }
        
        sql = "insert into orderdetails values('"+oid+"','"+oEmail+"','"+oCity+"',"+oPincode+",'"+oState+"','"+prodCode+"',"+Integer.parseInt(prodPrice)+")";
        stmt.executeUpdate(sql);
        new OrderConfirm(uname).setVisible(true);
        OrderConfirm.jLabel1.setText("Your Order has been confirmed with order number "+oid);
        this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
              
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Description(uname,pName).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(takeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(takeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(takeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(takeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new takeOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
